project_id = "rcebmiftdxxpbeiwbncb"

[functions]
[functions.create-paypal-subscription]
verify_jwt = true

[functions.paypal-webhook]
verify_jwt = false

[functions.generate-thread]
verify_jwt = true

[functions.generate-tweet]
verify_jwt = true

[functions.rate-limiter]
verify_jwt = true