// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcebmiftdxxpbeiwbncb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjZWJtaWZ0ZHh4cGJlaXdibmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NDY1NjQsImV4cCI6MjA1MDAyMjU2NH0.n1aq1NYm5GqpiRpNYZbYpMzxakOvexBDqgNCCIAhoB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);